version: '3.7'

services:
  order:
    build:
      context: ./services/order
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  payment:
    build:
      context: ./services/payment
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
