version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  order:
    build:
      context: ./services/order
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PASS=password
      - DB_PORT=5432
      - DB_NAME=orderdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ORDER_SERVICE_PORT=8080

  payment:
    build:
      context: ./services/payment
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - DB_USER=user
      - DB_PASS=password
      - DB_PORT=5432
      - DB_NAME=orderdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_SERVICE_PORT=8081
